use exit status of mpirun to better catch the runtime failure. also detect if pr ogram hang.

diff --git a/src/arch/mpi/charmrun b/src/arch/mpi/charmrun
--- a/src/arch/mpi/charmrun
+++ b/src/arch/mpi/charmrun
@@ -42,6 +42,8 @@ then
         script="charmrun_script.$$.sh"
         indir=`pwd`
         output="$indir/charmrun_script.$$.stdout"
+        result="$indir/charmrun_script.$$.result"
+	rm -f $result
         echo "Submitting batch job for> mpirun -np $pes $args"
         echo " using the command> qsub $script"
 	mpirun=`which mpirun`
@@ -65,16 +67,9 @@ $ppn
 #
 # This determines the wall-clock time limit (here 5 minutes):
 #PBS -l walltime=5:00
-
+#
 # Queue name (see info about other queues in web documentation)
 #PBS -q $PBS_QUEUE
-#
-# Export all my environment variables to the job
-##PBS -V
-#
-# Charge job to project abc (recommended for users with multiple projects)
-# [If project is invalid, a valid project will be automatically selected]
-##PBS -A abc
 #
 # Job name (default = name of script file)
 #PBS -N autobuild
@@ -89,7 +84,9 @@ cd $indir
 # This is the actual command to run the job:
 cat \$PBS_NODEFILE
 $mpirun -np $pes $extra $args
-echo STATUS: \$?
+# Save mpirun exit status
+status=\$?
+echo \$status > $result
 EOF
         chmod 755 $script
 	while [ -z "$jobid" ]
@@ -101,19 +98,16 @@ EOF
         while [ true ]
         do
                 qstat $jobid > tmp.$$
-                if test ! $? -eq 0 -a -f $output
+# Job ID does not exist now
+                if test $? -ne 0 -a -f $output
                 then
 # The job is done-- print its output
                         rm tmp.$$
-                        if `grep 'End of program' $output > /dev/null 2>/dev/null`
-			then
-				rm $script
-                        	exec cat $output
-			else
-				cat $output
-				rm -f $output 
-				exit 1
-			fi
+# When job hangs, result file does not exist
+			test -f $result && status=`cat $result` || status=1
+			cat $output
+			rm -f $script $result $output
+			exit $status
                 fi
 # The job is still queued or running-- print status and wait
                 tail -1 tmp.$$
