AMPI: Add pieglobals privatization method

diff --git a/src/libs/ck-libs/ampi/ampiCC b/src/libs/ck-libs/ampi/ampiCC
--- a/src/libs/ck-libs/ampi/ampiCC
+++ b/src/libs/ck-libs/ampi/ampiCC
@@ -86,6 +86,11 @@ do
      GLOBALS_SHARED='1'
      GLOBALS_FUNCPTR='1'
      ;;
+  -pieglobals)
+     GLOBALS='pie'
+     GLOBALS_SHARED='1'
+     GLOBALS_FUNCPTR='1'
+     ;;
 
   -c)
      EXPLICIT_COMPILATION='true'
@@ -137,6 +142,13 @@ then
   if [ "$CMK_SUPPORTS_PIPGLOBALS" != '1' ]
   then
     echo "Error: Prerequisites for -pipglobals support were not detected."
+    exit 1
+  fi
+elif [ "$GLOBALS" = 'pie' ]
+then
+  if [ "$CMK_SUPPORTS_PIEGLOBALS" != '1' ]
+  then
+    echo "Error: Prerequisites for -pieglobals support were not detected."
     exit 1
   fi
 fi
