when user gives a wrong arch name e.g. net-linux-bluegene, build should complain and abort.

diff --git a/build b/build
--- a/build
+++ b/build
@@ -242,11 +242,11 @@ do
   esac
 done
 
-[ "x$VERSION" = "x" ] && syntax
+[ "x$VERSION" = "x" ] && syntax && exit 1
 
 [ -z "$MAKE" ] && MAKE='make'
 
-[ -f $src/$BASEVERSION/conv-mach.h ] || syntax
+[ -f $src/$BASEVERSION/conv-mach.h ] || echo "Error> build can not find arch: $BASEVERSION!" && exit 1
 
 #generate VERSION name combining all the build-time options.
 if [ -n "$BOPTS" -o -n "$COMPILER" ]
