Build #1724: make bgclang the default compiler on all BGQ build targets
Change-Id: I4be24e79e728ee497cc2a783e39aef5c203bb08b

diff --git a/build b/build
--- a/build
+++ b/build
@@ -670,7 +670,12 @@ then
       echo '. $CHARMINC/'"cc-$i.sh" >> $ConvSh
 elif test `echo "$BASEVERSION" | grep -c "bluegeneq"` -gt 0
 then
-      i="xlc"
+      i="clang"
+      bgclang++11 --version
+      if [ $? -ne 0 ]; then
+         echo "ERROR: bgclang C/C++ compiler missing. Please load bgclang compilers, i.e. 'soft add +mpiwrapper-bgclang'."
+         exit 1
+      fi
       echo '#include "'cc-$i.h'"' >> $ConvHeader
       echo '. $CHARMINC/'"cc-$i.sh" >> $ConvSh
 fi
