build: Error out early if autoconf or automake are not installed and a configure script does not exist
Change-Id: I9cab38523239d2f388b2c0a32f4464cfb7e69f96

diff --git a/build b/build
--- a/build
+++ b/build
@@ -528,6 +528,15 @@ then
   exit 1
 fi
 
+if [ ! -f "$srcbaseabs/scripts/configure" ]
+then
+  if ! command -v autoreconf >/dev/null 2>&1 || ! command -v aclocal >/dev/null 2>&1
+  then
+    echo "Error> autoconf and automake are not installed."
+    exit 1
+  fi
+fi
+
 #generate header for uFcontext for the target VERSION
 UFCONTEXT_HEADER_NAME=
 if test `echo "$BASEVERSION" | grep -c "darwin"` -gt 0
