Added CMK_HAS_TYPEINFO if compiler supports typeof(). Fetch appropriate version of linux-smp libpthread based on glibc version.

diff --git a/src/scripts/charmconfig b/src/scripts/charmconfig
--- a/src/scripts/charmconfig
+++ b/src/scripts/charmconfig
@@ -553,9 +553,8 @@ t="test.cpp"
 test_cxx() {
         echo $ac_n "checking "$1"""... $ac_c" 1>&6
 echo "configure:556: checking "$1"" >&5
-	$CMK_CXX -I../include -c $t -o test.o > /dev/null 2>errs
-	
-	if test $? -eq 0 -a ! -s errs 
+	$CMK_CXX -I../include -c $t -o test.o > /dev/null 2>&1
+	if test $? -eq 0
 	then
                 echo "$ac_t"""$2"" 1>&6
 		pass="1"
@@ -565,7 +564,6 @@ echo "configure:556: checking "$1"" >&5
 		pass="0"
 		fail="1"
 	fi
-	rm errs
 }
 
 test_finish() {
@@ -698,6 +696,32 @@ cat >> confdefs.h <<EOF
 EOF
 
 
+
+cat > $t <<EOT
+#include <typeinfo>
+const char *foo(void) {
+	int x;
+	return typeid(x).name();
+}
+EOT
+test_cxx "whether typeinfo/typeid works" "ok" "no"
+cat >> confdefs.h <<EOF
+#define CMK_HAS_TYPEINFO $pass
+EOF
+
+
+cat > $t <<EOT
+namespace foo {
+	int x;
+};
+EOT
+test_cxx "whether namespaces work" "ok" "no"
+cat >> confdefs.h <<EOF
+#define CMK_NAMESPACES_BROKEN $fail
+EOF
+
+
+
 #test if we can have multiple delete like this
 cat > $t <<EOT
 class foo {
@@ -708,7 +732,7 @@ public:
 EOT
 test_cxx "whether operator delete can be overloaded in same class" "ok" "no"
 cat >> confdefs.h <<EOF
-#define CMK_MULTIPLE_DELETE $pass
+#define CMK_MULTIPLE_DELETE 0
 EOF
 
 
@@ -732,7 +756,7 @@ FCC=`echo $CMK_CF90 | cut -d' ' -f1`
 # Extract the first word of ""$FCC"", so it can be a program name with args.
 set dummy "$FCC"; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:736: checking for $ac_word" >&5
+echo "configure:760: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_FCL'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -761,7 +785,7 @@ fi
 if test -n "$FCL"
 then
   echo $ac_n "checking subroutine name used by Fortran compiler""... $ac_c" 1>&6
-echo "configure:765: checking subroutine name used by Fortran compiler" >&5
+echo "configure:789: checking subroutine name used by Fortran compiler" >&5
   if eval "test \"`echo '$''{'fortran_postfix'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -825,12 +849,12 @@ fi
 #go get libpthread.a from charm website
 if test $version = net-linux-smp  || test $version = mpi-linux-vmi || test $version = mpi-linux-vmi-pgcc
 then
-  if test ! -f ../lib/libpthread.a
+  if test ! -r ../lib/libpthread.a
   then
     # Extract the first word of "wget", so it can be a program name with args.
 set dummy wget; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:834: checking for $ac_word" >&5
+echo "configure:858: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_WGET'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -859,7 +883,7 @@ fi
     # Extract the first word of "lynx", so it can be a program name with args.
 set dummy lynx; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:863: checking for $ac_word" >&5
+echo "configure:887: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_LYNX'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -888,7 +912,7 @@ fi
     # Extract the first word of "telnet", so it can be a program name with args.
 set dummy telnet; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:892: checking for $ac_word" >&5
+echo "configure:916: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_TELNET'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -917,7 +941,7 @@ fi
     # Extract the first word of "uudecode", so it can be a program name with args.
 set dummy uudecode; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:921: checking for $ac_word" >&5
+echo "configure:945: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_prog_UUDECODE'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -946,25 +970,27 @@ fi
     
     CHARMIP='128.174.241.211'
 #    CHARMIP='charm.cs.uiuc.edu'
-    URL="http://${CHARMIP}/distrib/libpthread.a"
+    VERSION=`nm /lib/libc.so.6 | grep "A GLIBC_" | tail -1 | sed -e "s/00000000 A GLIBC_//g"`
+    L="libpthread-$VERSION.a"
+    URL="http://${CHARMIP}/distrib/$L"
     finish=0
-    printf "getting libpthread.a from $URL ..."
+    printf "getting $L from $URL ..."
     if test -n "$WGET"
     then
       printf "(wget) ..."
-      $WGET $URL > /dev/null 2>&1  && mv libpthread.a ../lib && finish=1
+      $WGET $URL > /dev/null 2>&1  && mv $L ../lib && finish=1
     fi
     if test $finish = 0 && test -n "$LYNX"
     then
       printf "(lynx) ..."
-      $LYNX -source $URL > libpthread.a 2>/dev/null && mv libpthread.a ../lib && finish=1
+      $LYNX -source $URL > $L 2>/dev/null && mv $L ../lib && finish=1
     fi
     if test $finish = 0 && test -n "$TELNET" && test -n "$UUDECODE"
     then
       printf "(telnet) ..."
       cat > get_libpthread <<EOT
 #! /bin/sh
-echo "GET /distrib/libpthread.uu 1.0"
+echo "GET /distrib/libpthread-$VERSION.uu 1.0"
 echo
 # exit normally when the telnet session closes.
 trap "exit 0" 13
@@ -973,14 +999,17 @@ while : ; do
  sleep 1
 done
 EOT
-      /bin/sh ./get_libpthread | ($TELNET $CHARMIP 80 > .uulib 2>/dev/null); $UUDECODE .uulib 2>/dev/null && rm -f .uulib && mv libpthread.a ../lib && finish=1
+      /bin/sh ./get_libpthread | ($TELNET $CHARMIP 80 > .uulib 2>/dev/null); $UUDECODE .uulib 2>/dev/null && rm -f .uulib && mv $L ../lib && finish=1
     fi
-    if test $finish = 0 || test ! -f ../lib/libpthread.a
+    ln -s $L ../lib/libpthread.a
+    if test $finish = 0 || test ! -r ../lib/libpthread.a
     then
       /bin/rm -f ../lib/libpthread.a
       echo "failed"
       echo "#####################################################################"
       echo "wget, lynx or telnet must be installed to get libpthread.a from charm website."
+      echo "Alternately, your version of GLIBC ($VERSION) is not yet supported--"
+      echo " contact ppl@cs.uiuc.edu for assistance."
       echo "#####################################################################"
       exit 1
     else
