Add a configure test for linking a Fortran program
If it fails, warn from charmc so that certain tests will skip their
Fortran components.

Change-Id: I26681072efce87186023f890b58f36351dea995e

diff --git a/src/scripts/charmc b/src/scripts/charmc
--- a/src/scripts/charmc
+++ b/src/scripts/charmc
@@ -1674,6 +1674,15 @@ then
 	CMK_LDXX_FLAGS="$CMK_F90MAINLIBS $CMK_LDXX_FLAGS"
 fi
 
+if [ -n "$F90_MAIN" -o "$USE_F90_LIBRARIES" = '1' ]
+then
+  if [ "$CMK_CAN_LINK_FORTRAN" != '1' ]
+  then
+    echo "Error: Configure testing was unable to link a Fortran program."
+    exit 1
+  fi
+fi
+
 ########################################################################
 #
 # Finalize command parameters
