update charmconfig.

diff --git a/src/scripts/charmconfig b/src/scripts/charmconfig
--- a/src/scripts/charmconfig
+++ b/src/scripts/charmconfig
@@ -900,7 +900,7 @@ then
         . ./conv-mach-opt.sh
 fi
 
-VERSION=050404
+VERSION=050405
 cat >>confdefs.h <<EOF
 #define CHARM_VERSION $VERSION
 EOF
@@ -1117,12 +1117,24 @@ cat >>confdefs.h <<EOF
 #define CMK_USE_POLL $pass
 EOF
 
+#test if has sys/mman.h
+cat > $t <<EOT
+#include <sys/types.h>
+#include <sys/mman.h>
+void foo(void) {
+}
+EOT
+test_cxx "whether it has sys/mman.h" "yes" "no"
+cat >>confdefs.h <<EOF
+#define CMK_HAS_MMAN_H $pass
+EOF
+
 #test fortran subroutine name
 FCC=`echo $CMK_CF90 | cut -d' ' -f1`
 
 # Extract the first word of ""$FCC"", so it can be a program name with args.
 set dummy "$FCC"; ac_word=$2
-echo "$as_me:1125: checking for $ac_word" >&5
+echo "$as_me:1137: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_FCL+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1137,7 +1149,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_FCL=""$FCC" "
-echo "$as_me:1140: found $ac_dir/$ac_word" >&5
+echo "$as_me:1152: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1145,16 +1157,16 @@ fi
 fi
 FCL=$ac_cv_prog_FCL
 if test -n "$FCL"; then
-  echo "$as_me:1148: result: $FCL" >&5
+  echo "$as_me:1160: result: $FCL" >&5
 echo "${ECHO_T}$FCL" >&6
 else
-  echo "$as_me:1151: result: no" >&5
+  echo "$as_me:1163: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
 if test -n "$FCL"
 then
-  echo "$as_me:1157: checking subroutine name used by Fortran compiler" >&5
+  echo "$as_me:1169: checking subroutine name used by Fortran compiler" >&5
 echo $ECHO_N "checking subroutine name used by Fortran compiler... $ECHO_C" >&6
   if test "${fortran_postfix+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1212,7 +1224,7 @@ EOF
 
 fi
 
-  echo "$as_me:1215: result: $fortran_postfix" >&5
+  echo "$as_me:1227: result: $fortran_postfix" >&5
 echo "${ECHO_T}$fortran_postfix" >&6
 fi
 
@@ -1223,7 +1235,7 @@ then
   then
     # Extract the first word of "wget", so it can be a program name with args.
 set dummy wget; ac_word=$2
-echo "$as_me:1226: checking for $ac_word" >&5
+echo "$as_me:1238: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_WGET+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1238,7 +1250,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_WGET="wget "
-echo "$as_me:1241: found $ac_dir/$ac_word" >&5
+echo "$as_me:1253: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1246,16 +1258,16 @@ fi
 fi
 WGET=$ac_cv_prog_WGET
 if test -n "$WGET"; then
-  echo "$as_me:1249: result: $WGET" >&5
+  echo "$as_me:1261: result: $WGET" >&5
 echo "${ECHO_T}$WGET" >&6
 else
-  echo "$as_me:1252: result: no" >&5
+  echo "$as_me:1264: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
     # Extract the first word of "lynx", so it can be a program name with args.
 set dummy lynx; ac_word=$2
-echo "$as_me:1258: checking for $ac_word" >&5
+echo "$as_me:1270: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_LYNX+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1270,7 +1282,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_LYNX="lynx "
-echo "$as_me:1273: found $ac_dir/$ac_word" >&5
+echo "$as_me:1285: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1278,16 +1290,16 @@ fi
 fi
 LYNX=$ac_cv_prog_LYNX
 if test -n "$LYNX"; then
-  echo "$as_me:1281: result: $LYNX" >&5
+  echo "$as_me:1293: result: $LYNX" >&5
 echo "${ECHO_T}$LYNX" >&6
 else
-  echo "$as_me:1284: result: no" >&5
+  echo "$as_me:1296: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
     # Extract the first word of "telnet", so it can be a program name with args.
 set dummy telnet; ac_word=$2
-echo "$as_me:1290: checking for $ac_word" >&5
+echo "$as_me:1302: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_TELNET+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1302,7 +1314,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_TELNET="telnet "
-echo "$as_me:1305: found $ac_dir/$ac_word" >&5
+echo "$as_me:1317: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1310,16 +1322,16 @@ fi
 fi
 TELNET=$ac_cv_prog_TELNET
 if test -n "$TELNET"; then
-  echo "$as_me:1313: result: $TELNET" >&5
+  echo "$as_me:1325: result: $TELNET" >&5
 echo "${ECHO_T}$TELNET" >&6
 else
-  echo "$as_me:1316: result: no" >&5
+  echo "$as_me:1328: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
     # Extract the first word of "uudecode", so it can be a program name with args.
 set dummy uudecode; ac_word=$2
-echo "$as_me:1322: checking for $ac_word" >&5
+echo "$as_me:1334: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_UUDECODE+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1334,7 +1346,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_UUDECODE="uudecode "
-echo "$as_me:1337: found $ac_dir/$ac_word" >&5
+echo "$as_me:1349: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1342,10 +1354,10 @@ fi
 fi
 UUDECODE=$ac_cv_prog_UUDECODE
 if test -n "$UUDECODE"; then
-  echo "$as_me:1345: result: $UUDECODE" >&5
+  echo "$as_me:1357: result: $UUDECODE" >&5
 echo "${ECHO_T}$UUDECODE" >&6
 else
-  echo "$as_me:1348: result: no" >&5
+  echo "$as_me:1360: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1478,7 +1490,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1481: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1493: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1645,7 +1657,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1648: error: ambiguous option: $1
+    { { echo "$as_me:1660: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1664,7 +1676,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1667: error: unrecognized option: $1
+  -*) { { echo "$as_me:1679: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1700,7 +1712,7 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "conv-autoconfig.h" ) CONFIG_HEADERS="$CONFIG_HEADERS conv-autoconfig.h" ;;
-  *) { { echo "$as_me:1703: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1715: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1770,7 +1782,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:1773: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:1785: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -1781,7 +1793,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1784: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1796: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1794,7 +1806,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1797: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1809: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -1911,7 +1923,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:1914: $ac_file is unchanged" >&5
+      { echo "$as_me:1926: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
