Added flag "-debug" to charmc for usage with charmdebug. Some work done on CmiReduce to make it possible to have concurrent reductions. Added memory tagging by chare ID in charmdebug. Fixed breakpointing with charmdebug: now each entry point is defined by its sequential index in the EP table (before a string match was performed). Added stepping: delivery of a single message in the queue. Also, all the system entry methods are currently always executed, and never get buffered by charmdebug (they can still breakpoint if the user so chooses). Fixed race condition in python interface. To do that the interface itself has been modified, in particular with regard to high-level python. Python is now more flexible and it allows any chare collection to be "python" and receive requests. The replies are reduced to a PythonCCS mainchare which will handle the socket. The python directory has now another module (charmdebug-python) for usage by charmdebug introspection code.

diff --git a/src/scripts/charmc b/src/scripts/charmc
--- a/src/scripts/charmc
+++ b/src/scripts/charmc
@@ -52,6 +52,8 @@ OPTS_LDXX=""
 OPTS_PIC="$CMK_PIC"
 test -z "$OPTS_PIC" && OPTS_PIC='-fpic'
 
+CHARMDEBUG=""
+LINK_PYTHON=""
 OBJECT=""
 POST_LANGUAGE=""
 POST_LIBRARIES=""    
@@ -311,6 +313,50 @@ printVersion()
 	echo Charm++ Version $version
 }
 
+
+##############################################################################
+#
+# The following section identifies CHARMBIN, the charm binary-directory.
+#
+##############################################################################
+
+ORIGDIR=`pwd`
+
+# Try to find CHARMBIN by looking in directory where charmc is
+
+findCharmBin $0
+
+FIRST_THREE=`uname -s | awk '{print substr($1,1,3)}' `
+if [ "$FIRST_THREE" = "CYG" ]
+then
+# Running on a windows system-- append .exe to file names
+	PROG_EXT=".exe"
+fi
+
+CHARMLIB="$CHARMBIN/../lib"
+CHARMINC="$CHARMBIN/../include"
+CHARMLIBSO=
+if test -d "$CHARMBIN/../lib_so" 
+then
+  CHARMLIBSO=`cd $CHARMBIN/../lib_so 2>/dev/null && pwd`
+  #getting absolute path is harder than thought because of symbolic links and ..
+  #ksh needs cd -P to resolve werid symbolic links, however -P is not portable
+  #csh is ok too if it exists 
+  test -z "$CHARMLIBSO" && CHARMLIBSO=`cd -P $CHARMBIN/../lib_so 2>/dev/null && pwd`
+  test -z "$CHARMLIBSO" && CHARMLIBSO=`csh -c "cd $CHARMBIN/../lib_so >& /dev/null && pwd"`
+  test -z "$CHARMLIBSO" && echo "$CHARMBIN/../lib_so: not found" && exit 1
+fi
+
+################################
+# Preload configuration script
+################################
+Debug "About to preload machine config script"
+Debug "Preload config script, setting defaults..."
+
+[ ! -r $CHARMINC/conv-config.sh ] && Abort "Cannot find conv-config.sh in $CHARMINC"
+. $CHARMINC/conv-config.sh $CHARMINC
+
+
 ##############################################################################
 #
 # Parse the arguments
@@ -367,6 +413,15 @@ do
 		esac
 		shift
 		;;
+
+        "-debug")
+                # Requested support from charmdebug: add some modules and libraries
+                CHARMDEBUG=1
+                MEMORY="charmdebug"
+                if [ -n "$CMK_BUILD_PYTHON" ]; then
+                    AddModules PythonCCS charmdebug_python
+                fi
+                ;;
 
 	"-module"|"-modules")
 		AddModules `echo $1 | sed -e 's/,/ /g'`
@@ -661,41 +716,10 @@ trap 'End 1' 2
 # Process original command-line arguments
 processArgs "$@"
 
-
-##############################################################################
-#
-# The following section identifies CHARMBIN, the charm binary-directory.
-#
-##############################################################################
-
-ORIGDIR=`pwd`
-
-# Try to find CHARMBIN by looking in directory where charmc is
-
-findCharmBin $0
-
-FIRST_THREE=`uname -s | awk '{print substr($1,1,3)}' `
-if [ "$FIRST_THREE" = "CYG" ]
-then
-# Running on a windows system-- append .exe to file names
-	PROG_EXT=".exe"
+# If we are debugging, add "-g -O0" to the C/C++ flags
+if [ -n "$CHARMDEBUG" ]; then
+    OPTS_CPP="$OPTS_CPP -O0 -g"
 fi
-
-CHARMLIB="$CHARMBIN/../lib"
-CHARMINC="$CHARMBIN/../include"
-CHARMLIBSO=
-if test -d "$CHARMBIN/../lib_so" 
-then
-  CHARMLIBSO=`cd $CHARMBIN/../lib_so 2>/dev/null && pwd`
-  #getting absolute path is harder than thought because of symbolic links and ..
-  #ksh needs cd -P to resolve werid symbolic links, however -P is not portable
-  #csh is ok too if it exists 
-  test -z "$CHARMLIBSO" && CHARMLIBSO=`cd -P $CHARMBIN/../lib_so 2>/dev/null && pwd`
-  test -z "$CHARMLIBSO" && CHARMLIBSO=`csh -c "cd $CHARMBIN/../lib_so >& /dev/null && pwd"`
-  test -z "$CHARMLIBSO" && echo "$CHARMBIN/../lib_so: not found" && exit 1
-fi
-
-
 
 ##############################################################################
 #
@@ -714,7 +738,11 @@ findModuleDep() {
 # HACK: add modules to both ends of library list, to avoid
 #  undefined symbol CkRegisterMainModule when it's in a module file.
 	POST_LIBRARIES=`AddList $POST_LIBRARIES -lmodule$M`
-	
+	if [ "$M" = "PythonCCS" ]
+            then
+            LINK_PYTHON=1
+        fi
+
 	dep=""
 # fixme: should search everything in the -L library paths:
 	for dir in `echo . $CHARMLIB`
@@ -763,6 +791,9 @@ Debug "Read config script, setting defaults..."
 . $CHARMINC/conv-config.sh $CHARMINC
 
 Debug "Setting vars..."
+
+# Now that we have read the config file, if python is requested, add the correct version
+POST_LIBRARIES=`AddList $POST_LIBRARIES -lpython${CMK_BUILD_PYTHON}`
 
 if [ "$BUILD_SHARE" = "1" ]
 then
