fixed the previous fix, suppress error output by using /dev/null

diff --git a/src/scripts/charmc b/src/scripts/charmc
--- a/src/scripts/charmc
+++ b/src/scripts/charmc
@@ -649,13 +649,13 @@ CHARMINC="$CHARMBIN/../include"
 CHARMLIBSO=
 if test -d "$CHARMBIN/../lib_so" 
 then
-  CHARMLIBSO=`cd $CHARMBIN/../lib_so && pwd`
-  # getting absolute path is harder than thought because of symbolic links
-  # ksh needs cd -P to resolve werid symbolic link, however -P is not portable
-  # csh is ok too if it exists 
-  test -z "$CHARMLIBSO" && CHARMLIBSO=`cd -P $CHARMBIN/../lib_so && pwd`
-  test -z "$CHARMLIBSO" && CHARMLIBSO=`csh -c "cd $CHARMBIN/../lib_so && pwd"`
-  test -z "$CHARMLIBSO" &&  exit 1
+  CHARMLIBSO=`cd $CHARMBIN/../lib_so 2>/dev/null && pwd`
+  #getting absolute path is harder than thought because of symbolic links and ..
+  #ksh needs cd -P to resolve werid symbolic links, however -P is not portable
+  #csh is ok too if it exists 
+  test -z "$CHARMLIBSO" && CHARMLIBSO=`cd -P $CHARMBIN/../lib_so 2>/dev/null && pwd`
+  test -z "$CHARMLIBSO" && CHARMLIBSO=`csh -c "cd $CHARMBIN/../lib_so >& /dev/null && pwd"`
+  test -z "$CHARMLIBSO" && echo "$CHARMBIN/../lib_so: not found" && exit 1
 fi
 
 
