charmc: Error out when attempting to use tlsglobals on uth
This will prevent tests/ampi/privatization from trying tlsglobals in
this circumstance.

Change-Id: I43767f42d56e88930399460dcefbd492d9ce916f

diff --git a/src/scripts/charmc b/src/scripts/charmc
--- a/src/scripts/charmc
+++ b/src/scripts/charmc
@@ -1363,6 +1363,11 @@ fi
 
 if [ "$TLSGLOBALS" = "1" ]
 then
+    if [ `cat $CHARMBIN/../tmp/.gdir` = "uth" ]
+    then
+      echo "Error: -tlsglobals is not supported with the uth machine layer."
+      exit 1
+    fi
     if ! `$CMK_CC --version | grep -q gcc`
     then
       echo "Warning: -tlsglobals may not work with compilers other than GCC."
