don't explicitly specify at link time to use -lmpi or -lmpich, let charmconfig test it.

diff --git a/src/scripts/configure.in b/src/scripts/configure.in
--- a/src/scripts/configure.in
+++ b/src/scripts/configure.in
@@ -655,7 +655,34 @@ test_cxx "whether build on MPI" "yes" "no" ""
 AC_DEFINE_UNQUOTED(CMK_BUILD_ON_MPI, $strictpass, [build MPI.])
 BUILD_MPI=$strictpass
 
-if test $strictpass -eq 1
+if test $BUILD_MPI -eq 1
+then
+  test_link "whether need to specify MPI library" "no" "yes" ""
+  if test $pass -ne 1
+  then
+    if test -z "$CMK_MPI_LIB"
+    then
+      test_link "whether -lmpich" "ok" "no" "-lmpich"
+      if test $pass -eq 1
+      then
+        add_flag CMK_SYSLIBS='"$CMK_SYSLIBS -lmpich"' "mpi lib"
+      else
+        test_link "whether -lmpi" "ok" "no" "-lmpi"
+        if test $pass -eq 1
+        then
+                add_flag CMK_SYSLIBS='"$CMK_SYSLIBS -lmpi"' "mpi lib"
+        else
+                echo "Error: can not find mpi library"
+                exit 1
+        fi
+      fi
+    else
+      add_flag CMK_SYSLIBS='"$CMK_SYSLIBS $CMK_MPI_LIB"' "mpi lib"
+    fi
+  fi
+fi
+
+if test $BUILD_MPI -eq 1
 then
 cat > $t <<EOT
 #include "mpi.h"
