Configure: Test for the appropriate MPI library to link
Don't specify whether to use -lmpi or -lmpich in each target's
scripts, since this can vary from one system or environment to
another. Instead, have the configure script test which one links
successfully.

diff --git a/src/scripts/configure.in b/src/scripts/configure.in
--- a/src/scripts/configure.in
+++ b/src/scripts/configure.in
@@ -643,6 +643,9 @@ test_cxx "whether __thread (Thread Local Storage) is supported" "yes" "no" ""
 AC_DEFINE_UNQUOTED(CMK_TLS_THREAD, $strictpass, [Allows __thread.])
 
 #### test if we can build MPI ####
+if test "$CMK_BUILD_MPI" = 1
+then
+
 cat > $t <<EOT
 #include "mpi.h"
 int main(int argc, char **argv)
@@ -655,7 +658,40 @@ test_cxx "whether build on MPI" "yes" "no" ""
 AC_DEFINE_UNQUOTED(CMK_BUILD_ON_MPI, $strictpass, [build MPI.])
 BUILD_MPI=$strictpass
 
-if test $strictpass -eq 1
+if test $BUILD_MPI -eq 0
+then
+  echo "Error: Can not compile a MPI program"
+  exit 1
+fi
+
+if test $BUILD_MPI -eq 1
+then
+  test_link "whether need to specify MPI library" "no" "yes" ""
+  if test $pass -ne 1
+  then
+    if test -z "$CMK_MPI_LIB"
+    then
+      test_link "whether -lmpich" "ok" "no" "-lmpich"
+      if test $pass -eq 1
+      then
+        add_flag CMK_SYSLIBS='"$CMK_SYSLIBS -lmpich"' "mpi lib"
+      else
+        test_link "whether -lmpi" "ok" "no" "-lmpi"
+        if test $pass -eq 1
+        then
+                add_flag CMK_SYSLIBS='"$CMK_SYSLIBS -lmpi"' "mpi lib"
+        else
+                echo "Error: can not find mpi library"
+                exit 1
+        fi
+      fi
+    else
+      add_flag CMK_SYSLIBS='"$CMK_SYSLIBS $CMK_MPI_LIB"' "mpi lib"
+    fi
+  fi
+fi
+
+if test $BUILD_MPI -eq 1
 then
 cat > $t <<EOT
 #include "mpi.h"
@@ -671,6 +707,7 @@ AC_DEFINE_UNQUOTED(CMK_MPI_INIT_THREAD, $strictpass, [Allows MPI_Init_thread.])
 fi
 mv -f ../include/mpi.h.bak ../include/mpi.h 2>/dev/null
 
+fi
 
 ################### Syscalls and Libraries ###################
 
