only test MPI build when CMK_BUILD_MPI is set in conv-common.sh

diff --git a/src/scripts/configure b/src/scripts/configure
--- a/src/scripts/configure
+++ b/src/scripts/configure
@@ -2403,6 +2403,9 @@ _ACEOF
 
 
 #### test if we can build MPI ####
+if test "$CMK_BUILD_MPI" = 1
+then
+
 cat > $t <<EOT
 #include "mpi.h"
 int main(int argc, char **argv)
@@ -2418,6 +2421,12 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 BUILD_MPI=$strictpass
+
+if test $BUILD_MPI -eq 0
+then
+  echo "Error: Can not compile a MPI program"
+  exit 1
+fi
 
 if test $BUILD_MPI -eq 1
 then
@@ -2466,6 +2475,7 @@ _ACEOF
 fi
 mv -f ../include/mpi.h.bak ../include/mpi.h 2>/dev/null
 
+fi
 
 ################### Syscalls and Libraries ###################
 
diff --git a/src/scripts/configure.in b/src/scripts/configure.in
--- a/src/scripts/configure.in
+++ b/src/scripts/configure.in
@@ -643,6 +643,9 @@ test_cxx "whether __thread (Thread Local Storage) is supported" "yes" "no" ""
 AC_DEFINE_UNQUOTED(CMK_TLS_THREAD, $strictpass, [Allows __thread.])
 
 #### test if we can build MPI ####
+if test "$CMK_BUILD_MPI" = 1
+then
+
 cat > $t <<EOT
 #include "mpi.h"
 int main(int argc, char **argv)
@@ -654,6 +657,12 @@ mv -f ../include/mpi.h ../include/mpi.h.bak 2>/dev/null
 test_cxx "whether build on MPI" "yes" "no" ""
 AC_DEFINE_UNQUOTED(CMK_BUILD_ON_MPI, $strictpass, [build MPI.])
 BUILD_MPI=$strictpass
+
+if test $BUILD_MPI -eq 0
+then
+  echo "Error: Can not compile a MPI program"
+  exit 1
+fi
 
 if test $BUILD_MPI -eq 1
 then
@@ -698,6 +707,7 @@ AC_DEFINE_UNQUOTED(CMK_MPI_INIT_THREAD, $strictpass, [Allows MPI_Init_thread.])
 fi
 mv -f ../include/mpi.h.bak ../include/mpi.h 2>/dev/null
 
+fi
 
 ################### Syscalls and Libraries ###################
 
