test if C program accept "inline"

diff --git a/src/scripts/configure b/src/scripts/configure
--- a/src/scripts/configure
+++ b/src/scripts/configure
@@ -1274,6 +1274,27 @@ echo "${ECHO_T}\"$4\"" >&6
 	fi
 }
 
+# Test: tries to compile C file $t (described by $1).
+#  If successful, prints $2 and sets $pass/clears $fail
+#  If failure, prints $3 and sets $pass/clears $fail
+#  additional arguments to c++ compiler are passed as $4
+test_cc() {
+        echo "$as_me:$LINENO: checking \"$1\"" >&5
+echo $ECHO_N "checking \"$1\"... $ECHO_C" >&6
+	$CMK_CC -I../include -I. $CMK_LIBDIR $CMK_INCDIR $OPTS_CC $OPTS_LD -c $t -o test.o $4 > out 2>&1
+	test_result $? "$1" "$2" "$3"
+ 	strictpass=$pass
+	strictfail=$fail
+        if test $pass -eq 1
+	then
+ 	  if cat out | grep -i "warn" > /dev/null 2>&1
+	  then
+	    strictpass="0" && strictfail="1"
+          fi
+        fi
+	/bin/rm -f out
+}
+
 # Test: tries to compile C++ file $t (described by $1).
 #  If successful, prints $2 and sets $pass/clears $fail
 #  If failure, prints $3 and sets $pass/clears $fail
@@ -1294,6 +1315,7 @@ echo $ECHO_N "checking \"$1\"... $ECHO_C" >&6
         fi
 	/bin/rm -f out
 }
+
 # Testlink: tries to compile and link a C++ file $t (described by $1).
 #  If successful, prints $2 and sets $pass/clears $fail
 #  If failure, prints $3 and sets $pass/clears $fail
@@ -1479,6 +1501,20 @@ _ACEOF
 
 
 ###################### C++ Compiler Features #####################
+
+#### check C inline ####
+cat > $t <<EOT
+inline static int foo()
+{
+  return 1;
+}
+EOT
+test_cc "whether inline works in C" "ok" "no" ""
+
+cat >>confdefs.h <<_ACEOF
+#define CMK_C_INLINE $pass
+_ACEOF
+
 
 #### check explicit ####
 cat > $t <<EOT
diff --git a/src/scripts/configure.in b/src/scripts/configure.in
--- a/src/scripts/configure.in
+++ b/src/scripts/configure.in
@@ -46,6 +46,26 @@ test_result() {
 	fi
 }
 
+# Test: tries to compile C file $t (described by $1).
+#  If successful, prints $2 and sets $pass/clears $fail
+#  If failure, prints $3 and sets $pass/clears $fail
+#  additional arguments to c++ compiler are passed as $4
+test_cc() {
+        AC_MSG_CHECKING("$1")
+	$CMK_CC -I../include -I. $CMK_LIBDIR $CMK_INCDIR $OPTS_CC $OPTS_LD -c $t -o test.o $4 > out 2>&1
+	test_result $? "$1" "$2" "$3"
+ 	strictpass=$pass
+	strictfail=$fail
+        if test $pass -eq 1
+	then 
+ 	  if cat out | grep -i "warn" > /dev/null 2>&1
+	  then 
+	    strictpass="0" && strictfail="1"
+          fi
+        fi
+	/bin/rm -f out
+}
+
 # Test: tries to compile C++ file $t (described by $1).
 #  If successful, prints $2 and sets $pass/clears $fail
 #  If failure, prints $3 and sets $pass/clears $fail
@@ -65,6 +85,7 @@ test_cxx() {
         fi
 	/bin/rm -f out
 }
+
 # Testlink: tries to compile and link a C++ file $t (described by $1).
 #  If successful, prints $2 and sets $pass/clears $fail
 #  If failure, prints $3 and sets $pass/clears $fail
@@ -224,6 +245,16 @@ test_cxx "whether ucontext has FPU pointer" "yes" "no" ""
 AC_DEFINE_UNQUOTED(CMK_CONTEXT_FPU_POINTER, $pass, [whether ucontext has pointer])
 
 ###################### C++ Compiler Features #####################
+
+#### check C inline ####
+cat > $t <<EOT
+inline static int foo()
+{
+  return 1;
+}
+EOT
+test_cc "whether inline works in C" "ok" "no" ""
+AC_DEFINE_UNQUOTED(CMK_C_INLINE, $pass, [whether C inline works in C])
 
 #### check explicit ####
 cat > $t <<EOT
