Added libmoduleseqpose A regular make will create both libmodulepose and libmoduleseqpose. libmoduleseqpose is just pose compiled with -DSEQUENTIAL_POSE=1. Which means you can't simply link via -module seqpose because the module linking system wants various registration functions to exist with the same name as the module.  Attempts to create standalone seqpose modules failed due to the bewildering variety of decl, def, etrans, and pose.h include file namespace agony which result in irreconcilable netsim link failures.
But this cheap hack work as long as you copy it over.
Therefore we also create a libmoduleorigpose copy of the libmodulepose
during the make so we can restore normality later.

The Makefiles for the netsims will have SEQUENTIAL options to take care
of this jiggery pokery (including etrans -s) behind the scenes.
BigNetSim is already done.  HiSim is a bit more complicated.
"Evil hidden from the user is indistinguishable from Good." - Jim Phillips

diff --git a/src/libs/ck-libs/pose/Makefile b/src/libs/ck-libs/pose/Makefile
--- a/src/libs/ck-libs/pose/Makefile
+++ b/src/libs/ck-libs/pose/Makefile
@@ -9,27 +9,49 @@ POSEINCDIR = $(CHARMINC)/pose
 
 # POSE object definitions - DO NOT MODIFY
 #***********************************
-OBJECTS=	eventID.o stats.o pose.o srtable.o cancel.o mempool.o \
+OBJECTS=	eventID.o stats.o srtable.o cancel.o mempool.o \
 		pvtobj.o lbObject.o ldbal.o gvt.o event.o eqheap.o \
 		evq.o sim.o rep.o strat.o seq.o cons.o opt.o opt2.o opt3.o \
-		spec.o adapt.o adapt2.o adapt3.o
+		spec.o adapt.o adapt2.o adapt3.o pose.o
+
 LIB = libmodulepose.a
+SEQLIB = libmoduleseqpose.a
 LIBDEST =  $(CDIR)/lib/$(LIB)
+LIBSEQDEST =  $(CDIR)/lib/$(SEQLIB)
 CIFILES = mempool.def.h gvt.def.h ldbal.def.h pose.def.h sim.def.h stats.def.h
 
 # POSE LIBRARY GENERATION RULES -
 # DO NOT MODIFY
 # *******************************
+
+all:  $(LIBDEST) $(LIBSEQDEST)
+
+pose: $(LIBDEST) 
+
+seqpose:  $(LIBSEQDEST) 
+
 $(LIBDEST):	$(OBJECTS)
-	$(CHARMC) -o $(LIBDEST) $(OBJECTS) 
+	$(CHARMC) -o $(LIBDEST) $(OBJECTS)
 	test ! -d $(POSEINCDIR) && mkdir $(POSEINCDIR) || true
 	/bin/cp -f  *.h $(POSEINCDIR)
 	/bin/cp libmodulepose.dep $(CDIR)/lib/.
+	/bin/cp $(CDIR)/lib/libmodulepose.a $(CDIR)/lib/libmoduleorigpose.a
+	/bin/cp $(CDIR)/lib_so/libmodulepose.so $(CDIR)/lib_so/libmoduleorigpose.so
+	/bin/cp -f  etrans.pl $(CHARMBIN)
+
+$(LIBSEQDEST): OPTS += -DSEQUENTIAL_POSE=1
+$(LIBSEQDEST): seqsync
+$(LIBSEQDEST): $(OBJECTS)
+	$(CHARMC) -o $(LIBSEQDEST) $(OBJECTS) 
+	test ! -d $(POSEINCDIR) && mkdir $(POSEINCDIR) || true
+	/bin/cp -f  *.h $(POSEINCDIR)
+	/bin/cp libmoduleseqpose.dep  $(CDIR)/lib/.
 	/bin/cp -f  etrans.pl $(CHARMBIN)
 
 # POSE COMPILATION RULES 
 # - DO NOT MODIFY
 #***********************
+
 
 sim.def.h : sim.decl.h
 
@@ -61,6 +83,7 @@ mempool.def.h: mempool.decl.h
 mempool.decl.h: mempool.ci
 	$(CHARMC) mempool.ci
 
+
 docs: pose.doxy adapt2.C adapt3.C eventID.C lbObject.C spec.C adapt2.h adapt3.h eventID.h lbObject.h pose.C spec.h pose.ci adapt.C ldbal.C srtable.C adapt.h mempool.C ldbal.ci srtable.h mempool.ci pose.h cancel.C stats.C cancel.h ldbal.h pvtobj.C stats.ci mempool.h pvtobj.h chpt.h seq.C cons.C evq.C rep.C stats.h seq.h cons.h evq.h opt2.C rep.h opt2.h strat.C eqheap.C gvt.C sim.C strat.h eqheap.h gvt.ci opt3.C sim.ci opt3.h event.C gvt.h opt.C sim.h event.h opt.h
 	doxygen pose.doxy
 
@@ -72,7 +95,21 @@ clean:
 	rm -f gmon.out #*#
 	rm -f core *~
 	rm -f TAGS *.headers
-	rm -f libpose.a
+	rm -f libmodulepose.a
+	rm -f libmoduleseqpose.a
+
+sqclean:
+	rm -f *.o
+	rm -f libmoduleseqpose.a
+
+#retarded but gets around the fact that make doesn't want to rebuild
+#these after the cleanup
+seqsync: sqclean
+	for i in $(OBJECTS) ; do \
+	        SRCFILE=`basename $$i .o`.C ; \
+		$(CHARMC) -o $$i $$SRCFILE ; \
+	done;
+
 
 include Make.depends
 
@@ -84,7 +121,7 @@ depends:  $(CIFILES)
            /bin/cp -f $(DEPENDFILE) $(DEPENDFILE).old; \
         fi; \
 	echo '#generated by make depends' > $(DEPENDFILE); \
-        for i in $(OBJECTS) ; do \
+        for i in $(PAROBJECTS) ; do \
 	      SRCFILE=`basename $$i .o`.C ; \
               echo "checking dependencies for $$SRCFILE" ; \
               g++ -MM -Wno-deprecated -I$(CHARMINC) $$SRCFILE >> $(DEPENDFILE); \
