now smart enough to create libraries and compound .o files.

diff --git a/src/charmc b/src/charmc
--- a/src/charmc
+++ b/src/charmc
@@ -15,6 +15,7 @@
 ############################################################################
 
 
+
 ##############################################################################
 #
 # Initialize the main controlling variables, then setup error handler
@@ -29,65 +30,8 @@ set FILES=
 set OBJECTFILES=
 set LIBRARIES=
 set CONVERSE=
+set DELETE=
 onintr failure
-
-##############################################################################
-#
-# The following section attempts to locate charm.
-#
-##############################################################################
-
-set ORIGDIR=$cwd
-
-# Try to find charm root by looking in directory where charmc is
-
-if ($?CHARMROOT == 0) then
-    set SCRIPT=$0
-    if ($SCRIPT:h != $SCRIPT:t) then
-        cd $SCRIPT:h
-        set SCRIPT=$SCRIPT:t
-    else
-        foreach dir ($path)
-            if (-x $dir/$SCRIPT && ! -d $dir/$SCRIPT) then
-                cd $dir
-                break
-            endif
-        end
-    endif
-    while (x`find $SCRIPT -type l -print` == x$SCRIPT)
-        set SCRIPT=`ls -al ./$SCRIPT:t | sed -e "s@.*-> @@"`
-        if ($SCRIPT:h != $SCRIPT:t) then
-            cd $SCRIPT:h
-            set SCRIPT=$SCRIPT:t
-        endif
-    end
-    cd ..
-    set CHARMROOT=`pwd`
-    if (! -e $CHARMROOT/include/conv-mach.csh) unset CHARMROOT
-    if (! -e $CHARMROOT/lib/libckn-core-notrace.a) unset CHARMROOT
-endif
-
-# Give an error message
-
-if ($?CHARMROOT == 0) then
-    echo ''
-    echo 'Error - cannot find the charm directories.'
-    echo ''
-    echo 'Normally, charmc and the other charm scripts automatically'
-    echo 'locate the charm directory, using the following strategy:'
-    echo ''
-    echo '  Step 1. It looks in the directory specified in $CHARMROOT.'
-    echo ''
-    echo '  Step 2. It looks in the directory from which charmc was run.'
-    echo ''
-    echo '  Step 3. It looks in every directory in your $PATH'
-    echo ''
-    echo 'If it searches all these places, and doesnt find the charm'
-    echo 'files, it will give up.'
-    echo ''
-    goto failure
-    endif
-endif
 
 ##############################################################################
 #
@@ -107,6 +51,12 @@ while ($argindex <= $#argv)
         case "-machine"
             set MACHTYPE=$argv[$argindex]
             @ argindex = $argindex + 1
+            breaksw
+
+        case "-cwd"
+            set CHARMBIN=.
+            set CHARMLIB=.
+            set CHARMINC=.
             breaksw
 
         case "-language"
@@ -253,22 +203,69 @@ end
 
 ##############################################################################
 #
-# Check for valid choice of MACHTYPE, and change CHARMROOT if necessary.
+# The following section identifies CHARMBIN, the charm binary-directory.
 #
 ##############################################################################
 
-if ($?MACHTYPE) then
-    if (-d $CHARMROOT/$MACHTYPE) then
-	set CHARMROOT=$CHARMROOT/$MACHTYPE
+set ORIGDIR=$cwd
+
+# Try to find CHARMBIN by looking in directory where charmc is
+
+if ($?CHARMBIN == 0) then
+    set SCRIPT=$0
+    if ($SCRIPT:h != $SCRIPT:t) then
+        cd $SCRIPT:h
+        set SCRIPT=$SCRIPT:t
     else
-       if (-d $CHARMROOT/../$MACHTYPE) then
-           set CHARMROOT=$CHARMROOT/../$MACHTYPE
-       else
-           echo 'error - there is no installed charm for "'$MACHTYPE'"'
-           goto failure
-       endif
+        foreach dir ($path)
+            if (-x $dir/$SCRIPT && ! -d $dir/$SCRIPT) then
+                cd $dir
+                break
+            endif
+        end
+    endif
+    while (x`find $SCRIPT -type l -print` == x$SCRIPT)
+        set SCRIPT=`ls -al ./$SCRIPT:t | sed -e "s@.*-> @@"`
+        if ($SCRIPT:h != $SCRIPT:t) then
+            cd $SCRIPT:h
+            set SCRIPT=$SCRIPT:t
+        endif
+    end
+    set CHARMBIN=`pwd`
+endif
+
+# Give an error message
+
+if ($?CHARMBIN == 0) then
+    echo ''
+    echo 'Error - cannot find the charm binary directory.'
+    echo ''
+    echo 'Normally, charmc and the other charm scripts automatically'
+    echo 'locate the charm binary directory, using the following strategy:'
+    echo ''
+    echo '  Step 1. It looks in the directory specified in $CHARMBIN'
+    echo ''
+    echo '  Step 2. It looks in the directory from which charmc was run.'
+    echo ''
+    echo 'If it searches both these places, and doesnt find the charm'
+    echo 'files, it will give up.'
+    echo ''
+    goto failure
     endif
 endif
+
+if ($?MACHTYPE) then
+    if (-d $CHARMBIN/../../$MACHTYPE/bin) then
+        cd $CHARMBIN/../../$MACHTYPE/bin
+	set CHARMBIN=`pwd`
+    else
+        echo 'error - there is no installed charm for "'$MACHTYPE'"'
+        goto failure
+    endif
+endif
+
+if ($?CHARMLIB == 0) set CHARMLIB=$CHARMBIN/../lib
+if ($?CHARMINC == 0) set CHARMINC=$CHARMBIN/../include
 
 ##############################################################################
 #
@@ -276,7 +273,7 @@ endif
 #
 ##############################################################################
 
-source $CHARMROOT/include/conv-mach.csh
+source $CHARMINC/conv-mach.csh
 
 if ($?OVERRIDE_CC) then
     set CMK_CC[1]=""
@@ -321,48 +318,223 @@ endsw
 
 ##############################################################################
 #
-# Check for valid choice of EXECMODE
-# Check for valid choice of QUEUE
-# Check for valid choice of BALANCE
+# Compile all specified files
+#
+# All temporary files named *.TMP.* for easy cleanup.
 #
 ##############################################################################
 
+cd $ORIGDIR
+
+foreach FILE ($FILES)
+  set BASE=$FILE:r
+  set TMP=$BASE:t.TMP
+  if ($?OBJECT == 0) set OBJECT=$BASE:t
+  if (${BASE}.o != $FILE) then
+      if ($?VERBOSE) echo "compiling $FILE."
+      /bin/rm -f $BASE.o $BASE.f.o
+  endif
+  switch ($FILE)
+    case "*.p"
+      if ($?VERBOSE) echo "$CMK_CPP $OPTS_CPP -I$CHARMINC $BASE.p > $TMP.cpp"
+      $CMK_CPP $OPTS_CPP -I$CHARMINC $BASE.p > $TMP.cpp
+      if ($?VERBOSE) echo "$CHARMBIN/charmfilter < $TMP.cpp | $CMK_M4 > $TMP.space"
+      $CHARMBIN/charmfilter < $TMP.cpp | $CMK_M4 > $TMP.space
+      if ($?VERBOSE) echo "$CHARMBIN/charmxlat $TMP.space $TMP.c"
+      $CHARMBIN/charmxlat $TMP.space $TMP.c
+      if ($status) goto failure
+      if ($?VERBOSE) echo "$CMK_CC $OPTS_CC -I$CHARMINC -c $TMP.c"
+      $CMK_CC $OPTS_CC -I$CHARMINC -c $TMP.c
+      if ($status) goto failure
+      if ($?NOLINK) then
+          if ($?VERBOSE) echo "/bin/mv $TMP.o $BASE.o"
+          /bin/mv $TMP.o $BASE.o
+      else
+          set OBJECTFILES=( $OBJECTFILES $TMP.o )
+      endif
+      breaksw
+    case "*.P"
+      echo 'extern "C" {' > $TMP.P.c
+      echo '#include <stdio.h>' >> $TMP.P.c
+      echo '}' >> $TMP.P.c
+      echo '#line 1 "'$BASE.P'"' >> $TMP.P.c
+      /bin/cat $BASE.P >> $TMP.P.c
+      if ($?VERBOSE) echo "$CMK_CPP $OPTS_CPP -I$CHARMINC $TMP.P.c > $TMP.cpp"
+      $CMK_CPP $OPTS_CPP -I$CHARMINC $TMP.P.c > $TMP.cpp
+      if ($?VERBOSE) echo "$CHARMBIN/charmfilter++ $TMP.cpp | $CMK_M4 > $TMP.space"
+      $CHARMBIN/charmfilter++ $TMP.cpp | $CMK_M4 > $TMP.space
+      if ($?VERBOSE) echo "$CHARMBIN/charmxlat++ $TMP.space $TMP.C"
+      $CHARMBIN/charmxlat++ $TMP.space $TMP.C
+      if ($status) goto failure
+      if ($?VERBOSE) echo "$CMK_CXX $OPTS_CPLUS -I$CHARMINC $TMP.C"
+      $CMK_CXX $OPTS_CPLUS -I$CHARMINC $TMP.C
+      if ($status) goto failure
+      if ($?NOLINK) then
+        if ($?VERBOSE) echo "/bin/mv $TMP.o $BASE.o"
+        /bin/mv $TMP.o $BASE.o
+      else
+        set OBJECTFILES=( $OBJECTFILES $TMP.o )
+      endif
+      breaksw
+    case "*.c"
+      if ($?VERBOSE) echo "$CMK_CC $OPTS_CC -I$CHARMINC -c $BASE.c"
+      $CMK_CC $OPTS_CC -I$CHARMINC -c $BASE.c
+      if ($status) goto failure
+      if ($?NOLINK == 0) then
+	set DELETE=( $DELETE $BASE.o )
+        set OBJECTFILES=( $OBJECTFILES $BASE.o )
+      endif
+      breaksw
+    case "*.C"
+      if ($?VERBOSE) echo "$CMK_CXX $OPTS_CPLUS -I$CHARMINC $BASE.C"
+      $CMK_CXX $OPTS_CPLUS -I$CHARMINC $BASE.C
+      if ($status) goto failure
+      if ($?NOLINK == 0) then
+        set DELETE=( $DELETE $BASE.o )
+        set OBJECTFILES=( $OBJECTFILES $BASE.o )
+      endif
+      breaksw
+    case "*.f"
+    case "*.F"
+    case "*.fc"
+    case "*.FC"
+      echo "charmc: I'm not yet smart enough to compile $FILE"
+      goto failure
+    case "*.o"
+      set OBJECTFILES=( $OBJECTFILES $BASE.o )
+      breaksw
+    default:
+      echo "file with unrecognized extension $FILE"
+      goto failure
+  endsw
+end
+
+
+##############################################################################
+#
+# Add module-init.TMP.o to OBJECTFILES if a MOD_LIST or MOD_FILE is specified.
+#
+##############################################################################
+
+if ( $?MOD_FILE ) then
+  if (! -e $MOD_FILE) then
+    echo 'No such module file '$MOD_FILE
+    goto failure
+  endif
+  if ( $?MOD_LIST ) then
+    echo 'You specified both -modules and -module_list, this is illegal.'
+    goto failure
+  endif
+  set MOD_LIST=(`cat $MOD_FILE`)
+endif
+
+if ( $?MOD_LIST ) then
+    rm -f module-init.TMP.c module-init.TMP.o
+    echo Modules: $MOD_LIST
+    echo " " > module-init.TMP.c
+    foreach i ( $MOD_LIST)
+      echo 'extern void _CK_'$i'_init();' >> module-init.TMP.c
+    end
+    echo '_CK_module_init_fn()' >> module-init.TMP.c
+      echo '{' >> module-init.TMP.c
+    foreach i ( $MOD_LIST)
+      echo '      _CK_'$i'_init();' >> module-init.TMP.c
+    end
+    echo '}' >> module-init.TMP.c
+    $CMK_CC $OPTS_CC -c module-init.TMP.c
+    if ($status) goto failure
+    set OBJECTFILES = ($OBJECTFILES module-init.TMP.o)
+endif
+
+##############################################################################
+#
+# Link-Step: there are three kinds of link-phases.
+#
+# 1. If $OBJECT is a ".a" file, a library is created from $OBJECTFILES.
+# 2. If $OBJECT is a ".o" file, then an "LDRO" is created from $OBJECTFILES.
+# 3. If $OBJECT is otherwise, then an executable is created.
+#
+##############################################################################
+
+if ($?NOLINK) goto success
+
+switch ($OBJECT)
+  case "*.o":
+    rm -f $OBJECT
+    if (($#FILES == 1)&&($#OBJECTFILES == 1)&&($OBJECT != $OBJECTFILES)) then
+        if ($?VERBOSE) echo mv $OBJECTFILES $OBJECT
+        mv $OBJECTFILES $OBJECT
+        if ($status) goto failure
+        if (! -e $OBJECT:r.$FILES:e) then
+            if ($?VERBOSE) echo ln -s $FILES $OBJECT:r.$FILES:e
+            ln -s $FILES $OBJECT:r.$FILES:e
+        endif
+    else
+        if ( $?VERBOSE ) echo $CMK_LDRO $OBJECT $OBJECTFILES
+        $CMK_LDRO $OBJECT $OBJECTFILES
+        if ($status) goto failure
+    endif
+    goto success
+
+  case "*.a":
+    if ( $?VERBOSE ) echo rm -f $OBJECT
+    rm -f $OBJECT
+    if ( $?VERBOSE ) echo $CMK_AR $OBJECT $OBJECTFILES
+    $CMK_AR $OBJECT $OBJECTFILES
+    if ($status) goto failure
+    if ( $?VERBOSE ) echo $CMK_RANLIB $OBJECT
+    $CMK_RANLIB $OBJECT
+    if ($status) goto failure
+    goto success
+
+  default:
+    goto exelink
+
+endsw
+
+##############################################################################
+#
+# Executable-Linking section.
+#
+# Check for valid choice of EXECMODE
+# Check for valid choice of QUEUE
+# Check for valid choice of BALANCE
+# Check for compatibility among BALANCE, QUEUE, and EXECMODE
+#
+##############################################################################
+
+exelink:
+
 if ($?EXECMODE == 0) set EXECMODE=notrace
 
-if (-e $CHARMROOT/lib/libckn-core-$EXECMODE.a) then
+if (-e $CHARMLIB/libckn-core-$EXECMODE.a) then
    set LIBCLASS=ckn
 else
-   if (-e $CHARMROOT/lib/libckd-core-$EXECMODE.a) then
+   if (-e $CHARMLIB/libckd-core-$EXECMODE.a) then
       set LIBCLASS=ckd
    else
       echo "charmc : No such execmode $EXECMODE"
-      (cd $CHARMROOT/lib ; ls -al libck?-core-*)
+      (cd $CHARMLIB ; ls -al libck?-core-*)
       goto failure
    endif
 endif
 
 if ($?QUEUE == 0) set QUEUE=fifo
 
-if (! -e $CHARMROOT/lib/libconv-qs-$QUEUE.a) then
+if (! -e $CHARMLIB/libconv-qs-$QUEUE.a) then
    echo "No queue strategy $QUEUE"
    echo "current choices are:
-   (cd $CHARMROOT/lib ; ls -al libconv-qs-*)
+   (cd $CHARMLIB ; ls -al libconv-qs-*)
    goto failure
 endif
 
 if ($?BALANCE == 0) set BALANCE=rand
 
-if (! -e $CHARMROOT/lib/lib${LIBCLASS}-ldb-$BALANCE.a) then
+if (! -e $CHARMLIB/lib${LIBCLASS}-ldb-$BALANCE.a) then
    echo "charmc : Unknown load balancer $BALANCE"
-   (cd $CHARMROOT/lib ; ls -al lib${LIBCLASS}-ldb-*)
+   (cd $CHARMLIB ; ls -al lib${LIBCLASS}-ldb-*)
    goto failure
 endif
-
-##############################################################################
-#
-# Check for compatibility among BALANCE, QUEUE, and EXECMODE
-#
-##############################################################################
 
 # Check that execmode is compatible with queue and balance
 
@@ -385,150 +557,6 @@ if ( $BALANCE == btok ) then
     endif
 endif
 
-##############################################################################
-#
-# Compile all specified files
-#
-# All temporary files named *.TMP.* for easy cleanup.
-#
-##############################################################################
-
-cd $ORIGDIR
-
-foreach FILE ($FILES)
-  set BASE=$FILE:r
-  set TMP=$BASE:t.TMP
-  if ($?OBJECT == 0) set OBJECT=$BASE:t
-  if (${BASE}.o != $FILE) then
-      echo "compiling $FILE."
-      /bin/rm -f $BASE.o $BASE.f.o
-  endif
-  switch ($FILE)
-    case "*.p"
-      if ($?VERBOSE) echo "$CMK_CPP $OPTS_CPP -I$CHARMROOT/include $BASE.p > $TMP.cpp"
-      $CMK_CPP $OPTS_CPP -I$CHARMROOT/include $BASE.p > $TMP.cpp
-      if ($?VERBOSE) echo "$CHARMROOT/bin/charmfilter < $TMP.cpp | $CMK_M4 > $TMP.space"
-      $CHARMROOT/bin/charmfilter < $TMP.cpp | $CMK_M4 > $TMP.space
-      if ($?VERBOSE) echo "$CHARMROOT/bin/charmxlat $TMP.space $TMP.c"
-      $CHARMROOT/bin/charmxlat $TMP.space $TMP.c
-      if ($status) goto failure
-      if ($?VERBOSE) echo "$CMK_CC $OPTS_CC -I$CHARMROOT/include -c $TMP.c -o $TMP.o"
-      $CMK_CC $OPTS_CC -I$CHARMROOT/include -c $TMP.c -o $TMP.o
-      if ($status) goto failure
-      if ($?NOLINK) then
-          if ($?VERBOSE) echo "/bin/mv $TMP.o $BASE.o"
-          /bin/mv $TMP.o $BASE.o
-      else
-          set OBJECTFILES=( $OBJECTFILES $TMP.o )
-      endif
-      breaksw
-    case "*.P"
-      echo 'extern "C" {' > $TMP.P.c
-      echo '#include <stdio.h>' >> $TMP.P.c
-      echo '}' >> $TMP.P.c
-      echo '#line 1 "'$BASE.P'"' >> $TMP.P.c
-      /bin/cat $BASE.P >> $TMP.P.c
-      if ($?VERBOSE) echo "$CMK_CPP $OPTS_CPP -I$CHARMROOT/include $TMP.P.c > $TMP.cpp"
-      $CMK_CPP $OPTS_CPP -I$CHARMROOT/include $TMP.P.c > $TMP.cpp
-      if ($?VERBOSE) echo "$CHARMROOT/bin/charmfilter++ $TMP.cpp | $CMK_M4 > $TMP.space"
-      $CHARMROOT/bin/charmfilter++ $TMP.cpp | $CMK_M4 > $TMP.space
-      if ($?VERBOSE) echo "$CHARMROOT/bin/charmxlat++ $TMP.space $TMP.C"
-      $CHARMROOT/bin/charmxlat++ $TMP.space $TMP.C
-      if ($status) goto failure
-      if ($?VERBOSE) echo "$CMK_CXX $OPTS_CPLUS -I$CHARMROOT/include $TMP.C -o $TMP.o"
-      $CMK_CXX $OPTS_CPLUS -I$CHARMROOT/include $TMP.C -o $TMP.o
-      if ($status) goto failure
-      if ($?NOLINK) then
-        if ($?VERBOSE) echo "/bin/mv $TMP.o $BASE.o"
-        /bin/mv $TMP.o $BASE.o
-      else
-        set OBJECTFILES=( $OBJECTFILES $TMP.o )
-      endif
-      breaksw
-    case "*.c"
-      if ($?VERBOSE) echo "$CMK_CC $OPTS_CC -I$CHARMROOT/include -c $BASE.c -o $BASE.o"
-      $CMK_CC $OPTS_CC -I$CHARMROOT/include -c $BASE.c -o $BASE.o
-      if ($status) goto failure
-      if ($?NOLINK == 0) then
-        if ($?VERBOSE) echo "/bin/mv $BASE.o $TMP.o"
-        /bin/mv $BASE.o $TMP.o
-        set OBJECTFILES=( $OBJECTFILES $TMP.o )
-      endif
-      breaksw
-    case "*.C"
-      if ($?VERBOSE) echo "$CMK_CXX $OPTS_CPLUS -I$CHARMROOT/include $BASE.c -o $BASE.o"
-      $CMK_CXX $OPTS_CPLUS -I$CHARMROOT/include $BASE.C -o $BASE.o
-      if ($status) goto failure
-      if ($?NOLINK == 0) then
-        if ($?VERBOSE) echo "/bin/mv $BASE.o $TMP.o"
-        /bin/mv $BASE.o $TMP.o
-        set OBJECTFILES=( $OBJECTFILES $TMP.o )
-      endif
-      breaksw
-    case "*.f"
-    case "*.F"
-    case "*.fc"
-    case "*.FC"
-      echo "charmc: I'm not yet smart enough to compile $FILE"
-      goto failure
-    case "*.o"
-      set OBJECTFILES=( $OBJECTFILES $BASE.o )
-      breaksw
-    default:
-      echo "file with unrecognized extension $FILE"
-      goto failure
-  endsw
-end
-
-
-##############################################################################
-#
-# Create module_init_fn.o
-#
-##############################################################################
-
-if ($?NOLINK) goto success
-
-if (-e module-init-fn.c) mv module-init-fn.c module-init-fn.bak
-
-if (( $?MOD_LIST == 0) && ( $?MOD_FILE )) then
-  if (! -e $MOD_FILE) then
-    echo 'No such module file '$MOD_FILE
-    goto failure
-  endif
-  set MOD_LIST=(`cat $MOD_FILE`)
-endif
-
-if (( $?MOD_LIST == 0) && ( -e module.list )) then
-  set MOD_LIST=(`cat module.list`)
-endif
-
-if ( $?MOD_LIST ) then
-    echo Modules: $MOD_LIST
-    echo " " > module-init-fn.c
-    foreach i ( $MOD_LIST)
-      echo 'extern void _CK_'$i'_init();' >> module-init-fn.c
-    end
-    echo '_CK_module_init_fn()' >> module-init-fn.c
-      echo '{' >> module-init-fn.c
-    foreach i ( $MOD_LIST)
-      echo '      _CK_'$i'_init();' >> module-init-fn.c
-    end
-    echo '}' >> module-init-fn.c
-    $CMK_CC $OPTS_CC -c module-init-fn.c
-    set OBJECTFILES = ($OBJECTFILES module-init-fn.o)
-else
-    echo 'Note: no module list specified.'
-endif
-
-##############################################################################
-#
-# Link
-#
-##############################################################################
-
-link:
-
 echo "linking $OBJECT with -language $LANGUAGE"
 
 set LIBRARIES = ($LIBRARIES \
@@ -545,13 +573,14 @@ else
    set LIBRARIES=(-l${LIBCLASS}-defmain $LIBRARIES)
 endif
 
-if ($?VERBOSE) echo "$LOADER $OPTS_LD -o $OBJECT $OBJECTFILES -L$CHARMROOT/lib $LIBRARIES"
-$LOADER $OPTS_LD -o $OBJECT $OBJECTFILES -L$CHARMROOT/lib $LIBRARIES
+if ($?VERBOSE) echo "$LOADER $OPTS_LD -o $OBJECT $OBJECTFILES -L$CHARMLIB $LIBRARIES"
+$LOADER $OPTS_LD -o $OBJECT $OBJECTFILES -L$CHARMLIB $LIBRARIES
+
 if ($status) goto failure
 
-if (-e $CHARMROOT/bin/conv-host) then
+if (-e $CHARMBIN/conv-host) then
     /bin/rm -f conv-host
-    /bin/ln -s $CHARMROOT/bin/conv-host conv-host
+    /bin/ln -s $CHARMBIN/conv-host conv-host
 endif
 
 goto success
@@ -561,7 +590,6 @@ goto success
 # Clean up files and exit
 #
 ########################################################################
-
 
 success:
     set STATUS=0
@@ -581,4 +609,5 @@ end:
             /bin/rm -f $TMP.c $TMP.c.0.h $TMP.c.1.h $TMP.c.2.h $BASE:t.headers
         end
     endif
+    rm -f core $DELETE
     exit ($STATUS)
